name = "nextname"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = ""

[build.environment_variables]
NODE_VERSION = "20"

[[pages]]
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

# KV namespace for caching
[[kv_namespaces]]
binding = "PRICING_CACHE"
id = "your_kv_namespace_id"
preview_id = "your_preview_kv_namespace_id"

# D1 database for persistent storage
[[d1_databases]]
binding = "PRICING_DB"
database_name = "domain-pricing-db"
database_id = "c55ac10b-bef8-4d90-b4f1-3fae72221fc3"