name = "nextname"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration
pages_build_output_dir = ".vercel/output/static"

# KV namespace for caching
[[kv_namespaces]]
binding = "PRICING_CACHE"
id = "9e7538c854bb477180154194a41934a6"
preview_id = "9e7538c854bb477180154194a41934a6"

# D1 database for persistent storage
[[d1_databases]]
binding = "PRICING_DB"
database_name = "domain-pricing-db"
database_id = "c55ac10b-bef8-4d90-b4f1-3fae72221fc3"

# Environment variables for data source configuration
[vars]
# Data source priority settings
D1_PRIORITY = "true"
D1_FRESHNESS_THRESHOLD_HOURS = "24"
ENABLE_SMART_FALLBACK = "true"
API_TIMEOUT_MS = "8000"
D1_TIMEOUT_MS = "5000"

# Cache configuration
CACHE_TTL = "3600"
SWR_WINDOW = "300"

# Page cache configuration (NEW)
ENABLE_PAGE_CACHE = "true"
PAGE_CACHE_TTL = "1800"         # 30 minutes for domain pages
SEARCH_CACHE_TTL = "900"        # 15 minutes for search results
TLD_CACHE_TTL = "86400"         # 24 hours for TLD pages
HOMEPAGE_CACHE_TTL = "600"      # 10 minutes for homepage

# Cache size limits
MAX_CACHE_SIZE_MB = "100"       # Maximum total cache size
CACHE_CLEANUP_THRESHOLD = "80"  # Cleanup when 80% full

# Performance monitoring
ENABLE_CACHE_STATS = "true"
ENABLE_PERFORMANCE_MONITORING = "true"