name = "nextname"
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = ""

[build.environment_variables]
NODE_VERSION = "20"

[[pages]]
compatibility_date = "2025-07-15"
compatibility_flags = ["nodejs_compat"]